### ISSUE TITLE
Add an 'any supported format' filter

### ISSUE THREAD

**Issue by Qqwy** [yasirkula/UnitySimpleFileBrowser#1]
We have used this with great success in our Global Game Jam 2017 game [Eye Can't Hear](http://globalgamejam.org/2017/games/eye-cant-hear).

One question/feature request though: We want players to be able to add any supported audio file. As such, we'd like a filter to allow the player to select any file having one of the `.mp3, .wav, .flac, .aiff, .ogg` extensions.

An 'any supported format' filter would be greatly appreciated.

**Comment by yasirkula** [comment]
Will do! Thanks for the suggestion.

**Comment by yasirkula** [comment]
I was busy with work. I will try to implement multi-filter feature soon, as well as a recycled list view for much better performance.

**Comment by yasirkula** [comment]
Update is now live.
