### ISSUE TITLE
Select multiple files

### ISSUE THREAD

**Issue by nezix** [yasirkula/UnitySimpleFileBrowser#10]
First, thanks for this awesome Asset !

Would it require a lot of work to allow selecting multiple files in a folder and obtain list of paths ?

**Comment by yasirkula** [comment]
A recycled list view (scroll view) is used to list the files. You'd need to tweak it to support selecting multiple files. Does it require a lot of work; I'm not sure. But I'm not planning to implement this feature myself at the moment :/

**Comment by nezix** [comment]
I gave it a try in my fork, branch named multipleFile : 

[https://github.com/nezix/UnitySimpleFileBrowser/tree/mutlipleFile](url)

I am pretty sure I added some bugs, and I did not closely respected all your code conventions but that's a first try :)

I will make a PR if you want me to.

**Comment by yasirkula** [comment]
Well done! A PR isn't needed at the moment but thank you for considering it.
