### ISSUE TITLE
Can it be used in MacOs?

### ISSUE THREAD

**Issue by v-osnovnom-bezvreden** [yasirkula/UnitySimpleFileBrowser#11]
Sorry if stuipid quiestion, couldnt any platforms related info.
Thank you!

**Comment by yasirkula** [comment]
Didn't test it on MacOS myself but it should work.

**Comment by daltonbr** [comment]
For posterity, I can confirm that indeed works on MacOS (Catalina 10.15.6).

My test config:

Unity 2020.1.3f1
UnitySimpleFileBrowser 1.3.0
