### ISSUE TITLE
can it be use in android game?

### ISSUE THREAD

**Issue by muafakul** [yasirkula/UnitySimpleFileBrowser#12]
i hope it can

**Comment by yasirkula** [comment]
Yes, it is supposed to work on Android.

**Comment by muafakul** [comment]
what i want is ,,iwant to change the sprite ,, imean something like changine the sprite of gameobject that contain spriterenderer ,,i want to make custom sprite where user can customize png image then applying to the game object through file manager

**Comment by yasirkula** [comment]
Does changing the "Filetype Icons" variable of the SimpleFileBrowserCanvas prefab not work for you?

**Comment by muafakul** [comment]
i still dont understad how to do , if there some scene example it woulbe
help me alot

Pada tanggal Rab, 1 Mei 2019 pukul 14.04 Süleyman Yasir KULA <
notifications@github.com> menulis:

**Comment by yasirkula** [comment]
![png](https://user-images.githubusercontent.com/10211608/57020545-3f704e00-6c32-11e9-8c13-6f133f062e5b.png)

**Comment by muafakul** [comment]
yes i know , but how to get the png image to replece some image on sprite
folder of the game ?

Pada tanggal Rab, 1 Mei 2019 pukul 20.58 Süleyman Yasir KULA <
notifications@github.com> menulis:

**Comment by muafakul** [comment]
so i have to do something here

   private void OnOperationSuccessful( string path )
        {
            Success = true;
            Result = path;

            //Hide();

            if( onSuccess != null )
                onSuccess( path );

            onSuccess = null;
            onCancel = null;
        }

but i dont know how to do bro

Pada tanggal Kam, 2 Mei 2019 pukul 02.51 Muafakul Khoir <
alhunaidah@gmail.com> menulis:

**Comment by muafakul** [comment]
![teach](https://user-images.githubusercontent.com/13078369/57040498-c43a8680-6c89-11e9-8d9b-aa9991043b63.PNG)

can you make example how to change that sprite ?

**Comment by yasirkula** [comment]
I see. You have to use the onSuccess event of the ShowLoadDialog function:

```csharp
FileBrowser.ShowLoadDialog( ( path ) =>
	{
		// Here, create a texture from the image at "path"
		// Google "unity load image runtime" to see how
	}, null );
```

**Comment by muafakul** [comment]
![correct](https://user-images.githubusercontent.com/13078369/57041385-47f57280-6c8c-11e9-8072-2e8613632dfe.PNG)
still failed ,,can you give me the correct example ?

**Comment by muafakul** [comment]
![can](https://user-images.githubusercontent.com/13078369/57042173-2b5a3a00-6c8e-11e9-9239-aee269844855.PNG)
can you give me spesific example ,please , i always failed , cry

**Comment by muafakul** [comment]
private void OnOperationSuccessful (string path) {
			Success = true;
			Result = path;

			//Hide();
			Debug.Log (path);
			if (onSuccess != null)
				onSuccess (path);

			onSuccess = null;
			onCancel = null;

			//LoadPNG(path);

			idontknow (path);
		}

		public void idontknow (string path) {

		//	FileBrowser.ShowLoadDialog ((path) => {
				// Here, create a texture from the image at "path"
				// Google "unity load image runtime" to see how

				Sprite tex = null;
				byte[] fileData;

				if (File.Exists (path)) {
					fileData = File.ReadAllBytes (path);
					tex = new Sprite ();
					//tex.LoadImage (fileData); //..this will auto-resize the texture dimensions.
					sr.sprite = tex;
				}
				//}

			//}, null);
		}



**still failded ,can you help me please ?**

**Comment by yasirkula** [comment]
```csharp
public void idontknow( string path ) 
{
	FileBrowser.ShowLoadDialog( ( path ) => 
	{
		if( File.Exists( path ) )
		{
			byte[] fileData = File.ReadAllBytes( path );
			Texture2D tex = new Texture2D( 2, 2 );
			tex.LoadImage( fileData );
			
			Sprite sprite = Sprite.Create( tex, new Rect( 0f, 0f, tex.width, tex.height ), new Vector2( 0.5f, 0.5f ), 100f );
			sr.sprite = sprite;
		}
	}, null );
}
```

**Comment by muafakul** [comment]
cool ,,is it possible to save sprite data in the player prefs or save load
playerinfo.bat

>

**Comment by yasirkula** [comment]
You can save the path of the file in PlayerPrefs. If you worry about the file getting deleted at some stage, you can copy it to Application.persistentDataPath via File.Copy and then save the path of the copied file.

**Comment by muafakul** [comment]
i will think about it ,and a lot of try and errors ,thanks

Pada tanggal Jum, 3 Mei 2019 pukul 23.31 Süleyman Yasir KULA <
notifications@github.com> menulis:
