### ISSUE TITLE
标题栏的bug

### ISSUE THREAD

**Issue by QQ648380421** [yasirkula/UnitySimpleFileBrowser#14]
如果标题栏的路径很长，启动时设置默认路径，那么窗口显示时会隐藏后面的路径，这种体验感并不友好，我修改了下脚本解决了这个问题
pathInputField.text = m_currentPath;
 pathInputField.ActivateInputField();
 pathInputField.Select();
StartCoroutine(MoveTextEnd_NextFrame());

   IEnumerator MoveTextEnd_NextFrame()
        {
            yield return new WaitForEndOfFrame() ;
            pathInputField.MoveTextEnd(false); 
            
        }

**Comment by QQ648380421** [comment]
![QQ截图20191118105024](https://user-images.githubusercontent.com/40554493/69020973-435a9680-09f1-11ea-860a-0d1f301493b9.png)

**Comment by yasirkula** [comment]
I see. You are right. I'll try to include your bugfix in a future release. I won't use it as is, though, since the ActivateInputField and Select functions would prompt the on-screen keyboard on mobile devices.

**Comment by QQ648380421** [comment]
Very good, will use frequently in the future, support your friend!

**Comment by yasirkula** [comment]
It doesn't seem possible to scroll the input field's text to the end without focusing on it first, I've tried changing caretPosition and/or calling MoveTextEnd. I don't think it is possible to resolve this issue without focusing on the input field using Unity's InputField class, so I'm closing this Issue.

BTW, your file browser looks really good!

**Comment by QQ648380421** [comment]
It doesn't matter, in fact, this problem is not very serious, when the mouse move up, I add a hover prompt on the line, also can have the same effect
