### ISSUE TITLE
File manager slows down.

### ISSUE THREAD

**Issue by Kniger33** [yasirkula/UnitySimpleFileBrowser#15]
Hello! I have a little problem: on some computers file manager slows down and opens directories for a long time (even on computers with ssd), but on most others it works good(even on computers with hard drive)(windows). What could be the problem? Thank you in advance.

**Comment by yasirkula** [comment]
Hmm, I'm not entirely sure. I'd recommend you to enable Deep Profiling and profile on a problematic device to see the function that takes the most CPU time.

**Comment by Kniger33** [comment]
> Hmm, I'm not entirely sure. I'd recommend you to enable Deep Profiling and profile on a problematic device to see the function that takes the most CPU time.

Okey, thanks

**Comment by yasirkula** [comment]
Feel free to reopen the issue with the data from Profiler.
