### ISSUE TITLE
Reopening FileBrowser in onSuccess or onCancel

### ISSUE THREAD

**Issue by Snonky** [yasirkula/UnitySimpleFileBrowser#16]
When calling `ShowLoadDialog `or `ShowSaveDialog `inside one of the callback functions to open a new dialog after the first one was closed, the `OnOperationSuccessful` or `OnOperationCanceled` method immediately sets the `onSucess `and `onCancel` members to null:

		private void OnOperationCanceled( bool invokeCancelCallback )
		{
			Success = false;
			Result = null;

			Hide();

			if( invokeCancelCallback && onCancel != null )
				onCancel(); // **Open new dialog here**

			onSuccess = null; // **It breaks because the callbacks are set to null**
			onCancel = null;
		}

Removing the last two lines of the method would allow "chaining" of dialogs.

**Comment by yasirkula** [comment]
I see, will fix it soon.
