### ISSUE TITLE
QuickLinks initialised before permission grant on Android

### ISSUE THREAD

**Issue by Chadys** [yasirkula/UnitySimpleFileBrowser#18]
Hello, first of all I love your asset and thank you for opensourcing it.
I think I discovered a little bug.

On Android, you need to ask for the `READ_EXTERNAL_STORAGE` permission to access, for example, the content of an external SD card. But, in [`FileBrowser.cs L.492`](https://github.com/yasirkula/UnitySimpleFileBrowser/blob/master/Assets/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L492), you call `InitializeQuickLinks` in the `Awake` function, before the user is asked for the permission to read files. Which means that the external SD card you may have, won't appear in the `QuickLinks` of the `SimpleFileBrowserCanvas`, even if the permission to access it has been given afterwards.

The bug is not blocking, since on all following app launches, if you don't revoke the permission of the app, you won't ever see it anymore. But it still would be better if it also worked the first time.

**Comment by yasirkula** [comment]
You are right! Pushing a fix now.

**Comment by Chadys** [comment]
Wow that's quick!
There is still a problem however.
I'm working on VR, using Wave SDK. Using that, you can't use the standard permission dialog, you need to use the one of the SDK. If `RequestPermission` is called on that platform, you'll get an app freeze since the dialog won't be visible.
Your fix has two problems: 
- the `FileBrowser.Awake` function will probably be called before another script can get a chance to call `FileBrowser.AskPermissions = false;`, hence causing a freeze
- if `AskPermissions` can be deactivated before, you won't get a freeze, but you'll once again get the bug I mentionned.

A better solution might be to call `InitializeQuickLinks` in the `Show` function, after the permission check, if it hasn't yet been initialised ?
