### ISSUE TITLE
Select file or folder

### ISSUE THREAD

**Issue by ahmkam** [yasirkula/UnitySimpleFileBrowser#19]
Is it possible to select either a file or a folder using the ShowLoadDialog? if i folder mode to **true** then I can't select a file even if I provide filters

**Comment by yasirkula** [comment]
You'd have to modify the source code, you can find all occurrences of _folderselectmode_ inside FileBrowser.cs and modify the script as you wish.

**Comment by yasirkula** [comment]
Added support in https://github.com/yasirkula/UnitySimpleFileBrowser/commit/6980dfdbfc09f91305d367f6904ec3bc9efd22fe
