### ISSUE TITLE
simple file browser for vr systems

### ISSUE THREAD

**Issue by alitokur** [yasirkula/UnitySimpleFileBrowser#22]
hi, is there any way to use this file browser for vr systems.
I tried some solutions, 
-using a pointer instead of a mouse.
-changing the canvas render mode "overlay to wordspace."
in generally some of my applications  work well, but "SimpleFileBrowserWindow" under the "SimpleFileBrowserCanvas" often cause problems.

**Comment by yasirkula** [comment]
Your workflow is correct. You just need to keep the file browser window active in your scene so that its Awake function is called and it sets itself as the singleton instance. You can deactivate the window in your Start function by calling `FileBrowser.Hide();` if you want. If you are already doing these, then what sort of problems are occurring?

**Comment by alitokur** [comment]
I'm doing this for a mobile app and using a eyeRaycast to select objects. If the pointer stays on the object for a certain time, it can select it. As you can see in the pictures, "TopView" and "BottomWiew" are working well. 

![issue_1](https://user-images.githubusercontent.com/20575896/80306222-9586bb80-87ca-11ea-9b61-0a6f2f932211.png)
![issue_2](https://user-images.githubusercontent.com/20575896/80306223-97e91580-87ca-11ea-89e1-b4b03a677064.png)
but I can't get any response in "MidWiew".

![issue_3](https://user-images.githubusercontent.com/20575896/80306229-9f102380-87ca-11ea-89ba-ca4a636c8497.png)

i guess, the problem is related to the eyeRaycast script I use.

```
 List<RaycastResult> raycastResults = new List<RaycastResult>();
        m_eventSystem.RaycastAll(m_pointerEvent, raycastResults);

        // Detect selectable
        if (raycastResults.Count > 0)
        {
            foreach(var result in raycastResults)
            {
                var newSelectable = result.gameObject.GetComponentInParent<Selectable>();

                if (newSelectable)
                {
                   // Debug.Log("seçilebilir");
                    if (newSelectable != m_excluded && newSelectable != m_currentSelectable)
                    {
                        Select(newSelectable);
                        m_currentRaycastResult = result;
                    }
                    break;
                } 
                    //Debug.Log("secilemez");
            }
        }
        else
        {
            if(m_currentSelectable || m_excluded)
            {
                Select(null, null);
            }
        }
```
When i use the "Selectable",  probably cannot select anything other than buttons,fields and scrollbar. This may be a weird issue so im sorry, this my first time with unit and c#.

**Comment by yasirkula** [comment]
Please make the following changes:

1. ListItem.cs

```csharp
using UnityEngine;

namespace SimpleFileBrowser
{
	[RequireComponent( typeof( RectTransform ) )]
	public class ListItem : UnityEngine.UI.Selectable
	{
		public object Tag { get; set; }
		public int Position { get; set; }

		private IListViewAdapter adapter;

		internal void SetAdapter( IListViewAdapter listView )
		{
			this.adapter = listView;
		}

		public override void Select()
		{
			base.Select();

			if( this is FileBrowserQuickLink )
				( (FileBrowserQuickLink) this ).OnPointerClick( null );
			else if( this is FileBrowserItem )
				( (FileBrowserItem) this ).OnPointerClick( null );
		}
		
		public void OnClick()
		{
			if( adapter.OnItemClicked != null )
				adapter.OnItemClicked( this );
		}
	}
}
```

2. FileBrowserItem.cs

```csharp
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

namespace SimpleFileBrowser
{
	public class FileBrowserItem : ListItem, IPointerClickHandler, IPointerEnterHandler, IPointerExitHandler
	{
		#region Constants
		private const float DOUBLE_CLICK_TIME = 0.5f;
		#endregion

		#region Variables
		protected FileBrowser fileBrowser;

#pragma warning disable 0649
		[SerializeField]
		private Image background;

		[SerializeField]
		private Image icon;

		[SerializeField]
		private Text nameText;
#pragma warning restore 0649

		private float prevTouchTime = Mathf.NegativeInfinity;
		#endregion

		#region Properties
		private RectTransform m_transform;
		public RectTransform TransformComponent
		{
			get
			{
				if( m_transform == null )
					m_transform = (RectTransform) transform;

				return m_transform;
			}
		}

		public string Name { get { return nameText.text; } }
		public bool IsDirectory { get; private set; }
		#endregion

		#region Initialization Functions
		public void SetFileBrowser( FileBrowser fileBrowser )
		{
			this.fileBrowser = fileBrowser;
		}

		public void SetFile( Sprite icon, string name, bool isDirectory )
		{
			this.icon.sprite = icon;
			nameText.text = name;

			IsDirectory = isDirectory;
		}
		#endregion

		#region Pointer Events
		public void OnPointerClick( PointerEventData eventData )
		{
			if( FileBrowser.SingleClickMode )
			{
				fileBrowser.OnItemSelected( this );
				fileBrowser.OnItemOpened( this );
			}
			else
			{
				if( Time.realtimeSinceStartup - prevTouchTime < DOUBLE_CLICK_TIME )
				{
					if( fileBrowser.SelectedFilePosition == Position )
						fileBrowser.OnItemOpened( this );

					prevTouchTime = Mathf.NegativeInfinity;
				}
				else
				{
					fileBrowser.OnItemSelected( this );
					prevTouchTime = Time.realtimeSinceStartup;
				}
			}
		}

		public override void OnPointerEnter( PointerEventData eventData )
		{
			base.OnPointerEnter( eventData );

#if UNITY_EDITOR || ( !UNITY_ANDROID && !UNITY_IOS )
			if( fileBrowser.SelectedFilePosition != Position )
				background.color = fileBrowser.hoveredFileColor;
#endif
		}

		public override void OnPointerExit( PointerEventData eventData )
		{
			base.OnPointerExit( eventData );

#if UNITY_EDITOR || ( !UNITY_ANDROID && !UNITY_IOS )
			if( fileBrowser.SelectedFilePosition != Position )
				background.color = fileBrowser.normalFileColor;
#endif
		}
		#endregion

		#region Other Events
		public new void Select()
		{
			background.color = fileBrowser.selectedFileColor;
		}

		public void Deselect()
		{
			background.color = fileBrowser.normalFileColor;
		}

		public void SetHidden( bool isHidden )
		{
			Color c = icon.color;
			c.a = isHidden ? 0.5f : 1f;
			icon.color = c;

			c = nameText.color;
			c.a = isHidden ? 0.55f : 1f;
			nameText.color = c;
		}
		#endregion
	}
}
```

**Comment by alitokur** [comment]
huh, fixed! thank you sir! 🙏

**Comment by yasirkula** [comment]
It must be related to ListItem now extending UnityEngine.UI.Selectable instead of MonoBehaviour. Can you check the code changes with that in mind? I'm currently unable to inspect this Issue due to my busy schedule.

**Comment by apvBri** [comment]
> huh, fixed! thank you sir! 🙏
Hi @alitokur, I know it has been 2 years since your reply.  But I'm also running into this issue when building for my Quest 2.  By any chance, what hardware did your changes work for? I'm wondering if it's not working for mine because I have updated hardware.

@yasirkula I tried using your exact code from ListFile.cs and FileBrowserItem.cs, and that didn't work. So then I reverted the changes so that it's the same as the updated codebase that is from the UnityAsset store. Then I made changes to incorporate some of the changes you made in this thread. I still can't get my Oculus 2 raycast to select items inside of the file browser window. 

Below are the current state of my scripts for ListFIle.cs and FileBrowserItem.cs. Just a note, the latest version of the FileBrowserItem.cs script from UnityAsset store had platform directives at the top of the script telling it to define which pointers for which platform. I removed the ones from the top of the script because I suspect they might be conflicting with the OVR Pointers.

My current ListItem.cs
`using UnityEngine;

namespace SimpleFileBrowser
{
	[RequireComponent( typeof( RectTransform ) )]
	public class ListItem : UnityEngine.UI.Selectable //MonoBehaviour
	{
		public object Tag { get; set; }
		public int Position { get; set; }

		private IListViewAdapter adapter;

		internal void SetAdapter( IListViewAdapter listView )
		{
			this.adapter = listView;
		}

        public override void Select()
        {
            base.Select();

            if (this is FileBrowserQuickLink)
                ((FileBrowserQuickLink)this).OnPointerClick(null);
            else if (this is FileBrowserItem)
                ((FileBrowserItem)this).OnPointerClick(null);
        }

        public void OnClick()
		{
			if( adapter.OnItemClicked != null )
				adapter.OnItemClicked( this );
		}
	}
}`


My current FileBrowserItem.cs

`using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

namespace SimpleFileBrowser
{
    public class FileBrowserItem : ListItem, IPointerClickHandler, IPointerDownHandler, IPointerUpHandler
//#if UNITY_EDITOR || (!UNITY_ANDROID && !UNITY_IOS)
        , IPointerEnterHandler, IPointerExitHandler
//#endif
    {
        #region Constants
        private const float DOUBLE_CLICK_TIME = 0.5f;
        private const float TOGGLE_MULTI_SELECTION_HOLD_TIME = 0.5f;
        #endregion

        #region Variables
        protected FileBrowser fileBrowser;

#pragma warning disable 0649
        [SerializeField]
        private Image background;

        [SerializeField]
        private Image icon;
        public Image Icon { get { return icon; } }

        [SerializeField]
        private Image multiSelectionToggle;

        [SerializeField]
        private Text nameText;
#pragma warning restore 0649

#pragma warning disable 0414
        private bool isSelected, isHidden;
#pragma warning restore 0414

        private UISkin skin;

        private float pressTime = Mathf.Infinity;
        private float prevClickTime;
        #endregion

        #region Properties
        private RectTransform m_transform;
        public RectTransform TransformComponent
        {
            get
            {
                if (m_transform == null)
                    m_transform = (RectTransform)transform;

                return m_transform;
            }
        }

        public string Name { get { return nameText.text; } }
        public bool IsDirectory { get; private set; }
        #endregion

        #region Initialization Functions
        public void SetFileBrowser(FileBrowser fileBrowser, UISkin skin)
        {
            this.fileBrowser = fileBrowser;
            OnSkinRefreshed(skin, false);
        }

        public void SetFile(Sprite icon, string name, bool isDirectory)
        {
            this.icon.sprite = icon;
            nameText.text = name;

            IsDirectory = isDirectory;
        }
        #endregion

        #region Messages
        private void Update()
        {
            if (fileBrowser.AllowMultiSelection && Time.realtimeSinceStartup - pressTime >= TOGGLE_MULTI_SELECTION_HOLD_TIME)
            {
                // Item is held for a while
                pressTime = Mathf.Infinity;
                fileBrowser.OnItemHeld(this);
            }
        }
        #endregion

        #region Pointer Events
        public void OnPointerClick(PointerEventData eventData)
        {
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_WEBGL || UNITY_WSA || UNITY_WSA_10_0
            if (eventData.button == PointerEventData.InputButton.Middle)
                return;
            else if (eventData.button == PointerEventData.InputButton.Right)
            {
                // First, select the item
                if (!isSelected)
                {
                    prevClickTime = 0f;
                    fileBrowser.OnItemSelected(this, false);
                }

                // Then, show the context menu
                fileBrowser.OnContextMenuTriggered(eventData.position);
                return;
            }
#endif

            if (Time.realtimeSinceStartup - prevClickTime < DOUBLE_CLICK_TIME)
            {
                prevClickTime = 0f;
                fileBrowser.OnItemSelected(this, true);
            }
            else
            {
                prevClickTime = Time.realtimeSinceStartup;
                fileBrowser.OnItemSelected(this, false);
            }
        }

        public void OnPointerDown(PointerEventData eventData)
        {
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_WEBGL || UNITY_WSA || UNITY_WSA_10_0
            if (eventData.button != PointerEventData.InputButton.Left)
                return;
#endif

            pressTime = Time.realtimeSinceStartup;
        }

        public void OnPointerUp(PointerEventData eventData)
        {
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_WEBGL || UNITY_WSA || UNITY_WSA_10_0
            if (eventData.button != PointerEventData.InputButton.Left)
                return;
#endif

            if (pressTime != Mathf.Infinity)
                pressTime = Mathf.Infinity;
            else if (fileBrowser.MultiSelectionToggleSelectionMode)
            {
                // We have activated MultiSelectionToggleSelectionMode with this press, processing the click would result in
                // deselecting this item since its selected state would be toggled
                eventData.eligibleForClick = false;
            }
        }

#if UNITY_EDITOR || (!UNITY_ANDROID && !UNITY_IOS)
        public void OnPointerEnter(PointerEventData eventData)
        {
            if (!isSelected)
                background.color = skin.FileHoveredBackgroundColor;
        }
#endif

#if UNITY_EDITOR || (!UNITY_ANDROID && !UNITY_IOS)
        public void OnPointerExit(PointerEventData eventData)
        {
            if (!isSelected)
                background.color = (Position % 2) == 0 ? skin.FileNormalBackgroundColor : skin.FileAlternatingBackgroundColor;
        }
#endif
        #endregion

        #region Other Events
        public void SetSelected(bool isSelected)
        {
            this.isSelected = isSelected;

            background.color = isSelected ? skin.FileSelectedBackgroundColor : ((Position % 2) == 0 ? skin.FileNormalBackgroundColor : skin.FileAlternatingBackgroundColor);
            nameText.color = isSelected ? skin.FileSelectedTextColor : skin.FileNormalTextColor;

            if (isHidden)
            {
                Color c = nameText.color;
                c.a = 0.55f;
                nameText.color = c;
            }

            if (multiSelectionToggle) // Quick links don't have multi-selection toggle
            {
                // Don't show multi-selection toggle for folders in file selection mode
                if (fileBrowser.MultiSelectionToggleSelectionMode && (!IsDirectory || fileBrowser.PickerMode != FileBrowser.PickMode.Files))
                {
                    if (!multiSelectionToggle.gameObject.activeSelf)
                    {
                        multiSelectionToggle.gameObject.SetActive(true);

                        Vector2 shiftAmount = new Vector2(multiSelectionToggle.rectTransform.sizeDelta.x, 0f);
                        icon.rectTransform.anchoredPosition += shiftAmount;
                        nameText.rectTransform.anchoredPosition += shiftAmount;
                    }

                    multiSelectionToggle.sprite = isSelected ? skin.FileMultiSelectionToggleOnIcon : skin.FileMultiSelectionToggleOffIcon;
                }
                else if (multiSelectionToggle.gameObject.activeSelf)
                {
                    multiSelectionToggle.gameObject.SetActive(false);

                    Vector2 shiftAmount = new Vector2(-multiSelectionToggle.rectTransform.sizeDelta.x, 0f);
                    icon.rectTransform.anchoredPosition += shiftAmount;
                    nameText.rectTransform.anchoredPosition += shiftAmount;

                    // Clicking a file shortly after disabling MultiSelectionToggleSelectionMode does nothing, this workaround fixes that issue
                    prevClickTime = 0f;
                }
            }
        }

        public void SetHidden(bool isHidden)
        {
            this.isHidden = isHidden;

            Color c = icon.color;
            c.a = isHidden ? 0.5f : 1f;
            icon.color = c;

            c = nameText.color;
            c.a = isHidden ? 0.55f : (isSelected ? skin.FileSelectedTextColor.a : skin.FileNormalTextColor.a);
            nameText.color = c;
        }

        public void OnSkinRefreshed(UISkin skin, bool isInitialized = true)
        {
            this.skin = skin;

            TransformComponent.sizeDelta = new Vector2(TransformComponent.sizeDelta.x, skin.FileHeight);
            skin.ApplyTo(nameText, isSelected ? skin.FileSelectedTextColor : skin.FileNormalTextColor);
            icon.rectTransform.sizeDelta = new Vector2(icon.rectTransform.sizeDelta.x, -skin.FileIconsPadding);

            if (isInitialized)
                SetSelected(isSelected);
        }
        #endregion
    }
}`
