### ISSUE TITLE
Out of memory error when getting audio file result

### ISSUE THREAD

**Issue by mdotstrange** [yasirkula/UnitySimpleFileBrowser#23]
Hello and thank you for the great tools! 

I'm getting a random out of memory error from line 341 of FileBrowserHelpers.cs
`			return File.ReadAllBytes(sourcePath);`

It appears it is called through me using  ` if (FileBrowser.Success)`

It happens randomly when loading audio files- file sizes from 1 megabyte to 50 megabytes will randomly get this error. The same audio file will randomly get the error if loaded in multiple times. Any idea on a direction for me to go to resolve this? Thank you for your time.

**Comment by yasirkula** [comment]
I'm guessing that the previously loaded audio clips stay in memory and at some point, device runs out of available RAM. If you are creating AudioClips using File.ReadAllBytes, try calling Destroy(previousAudioClip) for previously loaded audio clips so that they can be garbage collected.

**Comment by mdotstrange** [comment]
Thank you for the reply- I will give this a try- thanks again for all the great tools.
