### ISSUE TITLE
Request to add "Create Folder" button

### ISSUE THREAD

**Issue by alankley** [yasirkula/UnitySimpleFileBrowser#25]
It would be nice to optionally allow user to create a folder in current folder which the user could then select for return.

**Comment by yasirkula** [comment]
I agree that this is a useful feature but how will we create the folder? Essentially, it must be linked to a button on the UI for mobile and VR support. Any ideas on where to put the button? It should ideally be visible on mobile devices in portrait orientation, as well.

**Comment by alankley** [comment]
Perhaps a Create Folder button could go below the Show Hidden Files?
I've attached a screenshot of how MyFiles app on Android handles it.
They add it to a 3-dot more menu, if that is an option in your library. It would certainly fit well in portrait or landscape and offer more expansion for future desirable enhancements.

![MyFiles_NewFolder](https://user-images.githubusercontent.com/1298010/95814636-74664880-0ce0-11eb-887d-08e104bd3e8a.png)

**Comment by yasirkula** [comment]
A 3-dot is the most viable option. I may implement this feature later, thanks for bringing it up.

**Comment by alankley** [comment]
Thanks for considering adding this feature.
We really like your library, great job!

www.revealtech.ai
