### ISSUE TITLE
[Help wanted]

### ISSUE THREAD

**Issue by Jane-Tran** [yasirkula/UnitySimpleFileBrowser#26]
How to add default name when open dialog save file ?
Ths so much

**Platform specs**

- Unity version: *e.g. 2019.3.9f1*
- Platform: *Windows 10*
.

**Comment by yasirkula** [comment]
You can add this function to FileBrowser.cs and call it after showing the dialog:

```csharp
public static void SetFilename( string filename )
{
	Instance.filenameInputField.text = filename;
}
```

**Comment by Jane-Tran** [comment]
great answer
