### ISSUE TITLE
After loading a file Unity complains about two EventSystems in the scene

### ISSUE THREAD

**Issue by schub** [yasirkula/UnitySimpleFileBrowser#29]
Thanks for your great asset!!

Following your code example on github, I got it working instantly. Only one question. After loading a file, Unity complains that there are two EventSystems in the scene. 

How can I get rid of it? I have a Canvas and a UI and already an EventSytem in place.

**Comment by yasirkula** [comment]
This message is harmless but if you really don't want to see it, you can delete EventSystem from SimpleFileBrowserCanvas prefab and make sure that all scenes that you call FileBrowser from have an EventSystem object.

**Comment by schub** [comment]
Great!!! Thank you very much for the fast reply :)

**Comment by artur-ag** [comment]
I was facing the same problem. You can also make SimpleFileBrowser an _embedded_ package, and then change the SimpleFileBrowserCanvas prefab as needed. It's almost the same as copying the library into Assets, but it goes into the Package folder instead. And you'll need to add it to your source control, too, if you are using source control.
https://docs.unity3d.com/Manual/upm-embed.html

**Comment by hippogamesunity** [comment]
Hi! Just found this thread. I think this solution could be added to FAQ.

**Comment by yasirkula** [comment]
I may do that in a future update, thank you for the feedback!
