### ISSUE TITLE
have a way to show how much files exists in a folder?

### ISSUE THREAD

**Issue by frere97** [yasirkula/UnitySimpleFileBrowser#35]
hey man, there is a way to show how much files exists in a folder?

**Comment by frere97** [comment]
and sorry, i dont know how to not mark as a bug XD

**Comment by yasirkula** [comment]
You can use Directory.GetFiles (returns files), GetDirectories (returns folders) or GetFileSystemEntries (returns files and folders) to get contents of a folder. Then simply check the length of the array. If you want to display this information on SimpleFileBrowser dialog, then you will have to modify the SimpleFileBrowserCanvas prefab as you wish and update the Text you've created with validFileEntries.Count at the end of FileBrowser.RefreshFiles function.

**Comment by frere97** [comment]
thanks i will try this

**Comment by frere97** [comment]
i´ve made it, thanks man
