### ISSUE TITLE
File & folder name is incorrect on Korean

### ISSUE THREAD

**Issue by mingkyme** [yasirkula/UnitySimpleFileBrowser#39]
**Description of the bug**
<img width="287" alt="Screen Shot 2021-01-19 at 12 43 40 AM" src="https://user-images.githubusercontent.com/45954551/104936065-6155c980-59ef-11eb-8e4c-50294d30b343.png">
<img width="343" alt="Screen Shot 2021-01-19 at 12 43 50 AM" src="https://user-images.githubusercontent.com/45954551/104936080-67e44100-59ef-11eb-9c0a-32dcd13b7a73.png">

"부산시" <= That's folder name.

**Platform specs**
- Unity version: 2019.04.18f
- Platform: MAC
- Device: Mac OS
- How did you download the plugin:  Asset Store

**Comment by yasirkula** [comment]
Do you have to modify Unity's Text component in any way to display that name properly in the Text object? Can you create a new Text object and try displaying that name on it?

**Comment by mingkyme** [comment]
I didn't modify Text component.
It cause from one of korean(Hangul) feature.
'가' can be 2 codes.
Complete Hangul Code And Combine Hangul Code.
![스크린샷 2021-01-19 오전 9 22 21](https://user-images.githubusercontent.com/45954551/104973364-d8af4b80-5a37-11eb-9122-bde2a2a4e3d1.png)

'ㄱ' + 'ㅏ' => 가
OR
'가'

**Comment by yasirkula** [comment]
No I was asking you to create **GameObject-UI-Text** in your scene, paste the folder's name to that Text and see if it is rendered correctly. If you must tweak the Text's settings to render it correctly, please let me know of these changes.

**Comment by mingkyme** [comment]
<img width="739" alt="스크린샷 2021-01-20 오후 12 44 20" src="https://user-images.githubusercontent.com/45954551/105124307-3a95b100-5b1d-11eb-89a3-ea23d5a19a9c.png">
It's same.
I will PR for this issue.
