### ISSUE TITLE
"failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade" Error when i try to compile the project

### ISSUE THREAD

**Issue by MINECANGI** [yasirkula/UnitySimpleFileBrowser#40]
The pack works fine in PlayMode but when i can't compile this project

**Comment by yasirkula** [comment]
Can you check all error messages and copy all of their contents in full here?

**Comment by MINECANGI** [comment]
Sure,
-------------------------------------------------------------------------------
/!\ File C:\Users\showm\.android\repositories.cfg could not be loaded.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-------------------------------------------------------------------------------
Only this

**Comment by yasirkula** [comment]
I don't think it is related to NativeGallery. You can verify it by deleting NativeGallery from your project. You should google "`repositories.cfg could not be loaded`" instead.

**Comment by MINECANGI** [comment]
uh, sorry i mistook
there are 78 errors
'''UnityEditor.BuildPlayerWindow+BuildMethodException: 78 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x0027c] in <3b1af5075b0340cfb428dfcef292b2ea>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <3b1af5075b0340cfb428dfcef292b2ea>:0 
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()'''
is the last one

im so sorry

**Comment by yasirkula** [comment]
You are probably missing the actual error messages. Clear the console, attempt to build the game and then check Console. For **each** error message, click the error message and then copy **everything** from the **bottom part of the Console window**. I can't help you without seeing the actual error message. If the actual error message is "_repositories.cfg could not be loaded_", see https://github.com/yasirkula/UnitySimpleFileBrowser/issues/40#issuecomment-774075002.

**Comment by MINECANGI** [comment]
uh, sorry again
I have 78 Errors (and 20 warnings):
---

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
FAILURE: Build failed with an exception.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
* What went wrong:
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Execution failed for task ':launcher:processReleaseResources'.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
   > Android resource linking failed
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
     C:\Users\showm\VDCDJ\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:5:3-116: AAPT: error: attribute android:requestLegacyExternalStorage not found.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
* Try:
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
* Get more help at https://help.gradle.org
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
BUILD FAILED in 2s
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Configure project :launcher
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\package.xml. Probably the SDK is read-only
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:preBuild UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:preBuild UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:preReleaseBuild UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:compileReleaseAidl NO-SOURCE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:compileReleaseRenderscript NO-SOURCE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:generateReleaseResValues UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:generateReleaseResources UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:compileReleaseLibraryResources UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:processReleaseManifest
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:bundleLibRuntimeRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:mergeReleaseResources UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:javaPreCompileRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:processReleaseManifest
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
C:\Users\showm\VDCDJ\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:4:2-98 Warning:
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
	uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:4 to replace another declaration but no other declaration present
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
C:\Users\showm\VDCDJ\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:5:2-99 Warning:
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
	uses-permission#android.permission.WRITE_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:5 to replace another declaration but no other declaration present
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:packageReleaseAssets
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:mergeReleaseNativeLibs UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :unityLibrary:copyReleaseJniLibsProjectOnly UP-TO-DATE
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
> Task :launcher:processReleaseResources FAILED
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
30 actionable tasks: 4 executed, 26 up-to-date
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-5.6.4.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\showm\VDCDJ\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:5:3-116: AAPT: error: attribute android:requestLegacyExternalStorage not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[

> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :launcher:javaPreCompileRelease UP-TO-DATE

> Task :launcher:processReleaseManifest
C:\Users\showm\VDCDJ\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:4:2-98 Warning:
	uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:4 to replace another declaration but no other declaration present
C:\Users\showm\VDCDJ\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:5:2-99 Warning:
	uses-permission#android.permission.WRITE_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:5 to replace another declaration but no other declaration present

> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:mergeReleaseNativeLibs UP-TO-DATE
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
> Task :unityLibrary:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :launcher:processReleaseResources FAILED
30 actionable tasks: 4 executed, 26 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <5f8140421e7d41ada100b629c3033aa7>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <5f8140421e7d41ada100b629c3033aa7>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <5f8140421e7d41ada100b629c3033aa7>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
Build completed with a result of 'Failed'
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
UnityEditor.BuildPlayerWindow+BuildMethodException: 78 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x0027c] in <3b1af5075b0340cfb428dfcef292b2ea>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <3b1af5075b0340cfb428dfcef292b2ea>:0 
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-
I've only included the errors
---

**Comment by yasirkula** [comment]
The actual error message is "`error: attribute android:requestLegacyExternalStorage not found`". Please check out the relevant [FAQ](https://github.com/yasirkula/UnitySimpleFileBrowser#faq) entry about it.

**Comment by MINECANGI** [comment]
I finally solved this problem!
Thank you so much!!!

**Comment by yasirkula** [comment]
Glad to hear it 😺
