### ISSUE TITLE
All I can select is folder ONLY.

### ISSUE THREAD

**Issue by naive231** [yasirkula/UnitySimpleFileBrowser#5]
OS: Android 4.4.2
CPU: RK3288
I paste the sample codes, build the apk, and install it to my system.
Dialog shows, I can switch to every folder I want, but I can't see and **files**.
Is that a bug?

**Comment by yasirkula** [comment]
I suspect that either the file filter was set to '.*jpg' and you didn't have any .jpg files in the directories you browsed or folderMode was set to true in the ShowLoadDialog/WaitForLoadDialog function.
