### ISSUE TITLE
Not working perfectly in iOS

### ISSUE THREAD

**Issue by SrejonKhan** [yasirkula/UnitySimpleFileBrowser#51]
**Description of the bug**

In iOS, files are not showing as expected. Some folders are showing, but not regular folders like photos or users folder. 

Also, it's possible to create a folder from the runtime, but it's not found in the iPhone default file browser. 

**Reproduction steps**
Used the following code in a coroutine -
```csharp
  FileBrowser.SetFilters(true, new FileBrowser.Filter("Image", ".jpg", ".png", "public.image"), new FileBrowser.Filter("PDF", ".pdf"));
  FileBrowser.SetDefaultFilter(".png");

  yield return FileBrowser.WaitForLoadDialog(FileBrowser.PickMode.Files, false);

  if (FileBrowser.Success)
  {
      string filePath = FileBrowser.Result[0];
      Debug.Log("File Path - " + filePath);
      //my codes here
  }
```
Result- 
![issue_ios](https://user-images.githubusercontent.com/57011529/122636642-21188580-d10c-11eb-8513-e184d30fc1e0.jpg)
![issue_ios2](https://user-images.githubusercontent.com/57011529/122636734-9e43fa80-d10c-11eb-9fbc-2867092254e6.jpg)

**Platform specs**

- Unity version: *2019.4.7f1*
- Platform: *iOS*
- Device: *IPhone 12 Pro Max ver. 14.5*
- Target Min iOS Version: *11*
- How did you download the plugin: *GitHub*

**Comment by yasirkula** [comment]
iOS restricts access to important folders like Photos. You have full access to your app's own directory and some other iOS directories (press the up arrow key multiple times and you'll see those directories). For image/video interactions, I'd recommend using [NativeGallery](https://github.com/yasirkula/UnityNativeGallery).
