### ISSUE TITLE
Duplicate error on build

### ISSUE THREAD

**Issue by Fennlin** [yasirkula/UnitySimpleFileBrowser#52]
**Description of the bug**

We have updated to version 1.4.7 but, for some reason, we are getting an error saying we have duplicate classes on "com.yarsikula.unity.FileBrowserPermissionReceiver" and "com.yarsikula.unity.FileBrowserPermissionFragment" found in modules SimpleFileBrowser.jar and Classes.jar.
Is there a way to fix this?

- Unity version: 2019.4.15

**Comment by yasirkula** [comment]
Simply delete _SimpleFileBrowser.jar_. If you haven't customized any of the files inside the plugin, then I'd recommend you to delete the plugin completely and reimport it.

**Comment by Fennlin** [comment]
Hi!
Alright, so... We tried to update FileBrowser to try and fix an issue with having access denied on Android folders. And because of the update, we had this issue with the duplicate items. I did what you told me to and it fixed the problem with the duplicates, but sadly updating did not help with the problem of denied access.
Would you have any idea of what it could be? (Should I open another issue or is it okay to keep things here?)

**Comment by yasirkula** [comment]
Can you create a new Issue with as much information as you can provide, like stacktrace, OS version and so on?

**Comment by Fennlin** [comment]
Sure! I'll gather all info I can and make a new one! Thanks for also helping with this one!
