### ISSUE TITLE
InputSystem does not exist in the namespace

### ISSUE THREAD

**Issue by jrdndj** [yasirkula/UnitySimpleFileBrowser#55]
**Description of the bug**

Filebrowser.cs(10,19): error CS0234: the type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine'. 

Also happens in FileBrowserDeleteConfirmationPanel and FileBrowserRenamedItem. 

**Reproduction steps**

I just downloaded and imported SimpleFileBrowser into my project. And it is generating these errors. I am using the latest InputSystem since I need to using some keypresses as input to my unity project. 

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *20194.12f1*
- Platform: Mac OS BigSur 
- Device: NA Macbook Pro 2016 with touchbar 
- How did you download the plugin: Package Manager 

**Additional info**

NA

Thank you and have a nice day!

**Comment by Flavelius** [comment]
@yasirkula if you add the inputsystem package as a reference to the asmdef, you can remove the requirement of the package needing to be in the asset folder. For users not having the input package installed unity will silently ignore it, so there's no downside to doing that.

**Comment by yasirkula** [comment]
Back then, I didn't follow this approach due to [backwards compatibility](https://github.com/yasirkula/UnityIngameDebugConsole/pull/32#issuecomment-735395202). Now I don't need to worry about that too much but there's still the issue with EventSystem. It still needs to be modified manually. In which case, since a one-time setup is always required, I'm considering keeping things as is. What do you think?

**Comment by Flavelius** [comment]
I would say there's no downside to doing it, as it doesn't change the outcome (no sideeffects) for people not using it inside a package, the notes could even be left as is.
Using your asset inside a package though currently requires manually re-adding the asmdef reference after every update, which is easy to miss, so it would be appreciated to have that set by default.

**Comment by yasirkula** [comment]
What about EventSystem though? Doesn't it require the asset to be imported as a standard asset (rather than a package) and then modifying it by hand in any case?

**Comment by yasirkula** [comment]
Actually, if the scene already has a properly configured EventSystem, it shouldn't be necessary to update the EventSystem inside this plugin thanks to [EventSystemHandler](https://github.com/yasirkula/UnitySimpleFileBrowser/blob/master/Plugins/SimpleFileBrowser/Scripts/EventSystemHandler.cs). But I can't remember if Unity logs warnings to the console at runtime/edit time if we don't upgrade the embedded EventSystem. Did you encounter any warnings if you didn't update the EventSystem?

**Comment by Flavelius** [comment]
You could conditionally replace incompatible components in code via custom version defines set in the asmdef with reference to the input system (https://docs.unity3d.com/Manual/class-AssemblyDefinitionImporter.html#version-defines), that way it will work no matter how different unity versions might handle that.

**Comment by yasirkula** [comment]
Added proper new Input System support in the latest version 🎮
