### ISSUE TITLE
It seems impossible to select all files and not show them all, like this

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnitySimpleFileBrowser#56]
![image](https://user-images.githubusercontent.com/50401776/140009032-78f4f0da-ffcb-4ee4-8dea-42aaee9363a1.png)

**Comment by yasirkula** [comment]
Can you please elaborate? We can see all files with the "All Files" filter and select them all via CTRL+A or the context menu at the top right. `allowMultiSelection` must be set to true, though.

**Comment by ShenKang4181** [comment]
My code :
FileBrowser.SetFilters( true );  
FileBrowser.ShowLoadDialog( OnSelectBaoJiaWuLiao , null , FileBrowser.PickMode.Files , true , null , null , "选择报价物料单文件" , "确定" ); 
runtime :
![image](https://user-images.githubusercontent.com/50401776/140021496-16360c2f-a13d-45af-a280-990965fce4ef.png)

I want to customize "all files(.*)" text

**Comment by yasirkula** [comment]
Ah! You can customize these 3 public static variables from your scripts (`FileBrowser.AllFilesFilterText = "blabla";`):

https://github.com/yasirkula/UnitySimpleFileBrowser/blob/333c21cbf0acc31e049bfa4b1e84abb57ed200e2/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L233-L234

https://github.com/yasirkula/UnitySimpleFileBrowser/blob/333c21cbf0acc31e049bfa4b1e84abb57ed200e2/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L259-L260

https://github.com/yasirkula/UnitySimpleFileBrowser/blob/333c21cbf0acc31e049bfa4b1e84abb57ed200e2/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L276-L277

**Comment by ShenKang4181** [comment]
I did it! Thank you. Love you
