### ISSUE TITLE
Issue with Unity 2017.3.0

### ISSUE THREAD

**Issue by huspau** [yasirkula/UnitySimpleFileBrowser#6]
Hi,

I love your code and I used it for 5.6 but when I upgraded unity to the latest one, when I use your plugins it does not show all files in a folder. Because of that, the plugin is unusable.

**Comment by yasirkula** [comment]
Thanks for letting me know. It was a rather interesting bug related to using localPosition on UI elements. Using anchoredPosition instead solved the issue for me. 

I've updated the plugin accordingly. Let me know if the issue persists.
