### ISSUE TITLE
Documentation fails to mention how to re-wrap aar

### ISSUE THREAD

**Issue by SavedByZero** [yasirkula/UnitySimpleFileBrowser#60]
Hey,

There are instructions about how to edit the .aar bundle to remove a line from AndroidManifest, but none about how to re-wrap it; neither 7-zip nor WinRar offer this archiving format.

**Comment by SavedByZero** [comment]
eh, I got the upgrade working despite Unity's bugginess around updating SDKs, don't worry about it.

**Comment by yasirkula** [comment]
I myself simply open the .aar with 7-zip or WinRAR, double click the AndroidManifest, modify it, and then when I return to the opened archive, say Yes to the "Should the archive be updated?" dialog.
