### ISSUE TITLE
Why there is no single example scene as usually we found on Unity asset packages?

### ISSUE THREAD

**Issue by habibieamrullah** [yasirkula/UnitySimpleFileBrowser#61]
It seems promising. I've heard many people said it is great. But for me, as long as I can not try some example scenes in this package, it's hard to me how to get started using it.

**Comment by yasirkula** [comment]
I hope you find the [example code](https://github.com/yasirkula/UnitySimpleFileBrowser#example-code) useful.

**Comment by habibieamrullah** [comment]
You are right. I placed the example code on a game object on my scene then everything works very well. Thank you, man, the best work helped me a lot.
