### ISSUE TITLE
Making a confirmation panel for save file override.

### ISSUE THREAD

**Issue by visca-c** [yasirkula/UnitySimpleFileBrowser#62]
Does the current package handle save file override confirmation? I see that the prefab has a delete confirmation panel, it would be nice to have a save file override confirmation panel too. Currently it's hard to check before saving since I can only get file paths when OnSuccess happens.

**Comment by yasirkula** [comment]
It doesn't but it'd be a nice feature.

**Comment by hippogamesunity** [comment]
+1
