### ISSUE TITLE
Suggestion: accept full paths in filename input field

### ISSUE THREAD

**Issue by artur-ag** [yasirkula/UnitySimpleFileBrowser#63]
In the native Windows file dialog, if you type a full path in the filename input field instead of just a filename, it will follow the full path and open the file. But in the current version of SimpleFileBrowser, if you do this, the field just turns red and nothing happens. I think this feature would be very useful, because it allows the user to copy a file's full path on Windows Explorer (Shift+Right Click, Copy as path), paste it directly on SimpleFileBrowser, and press Enter to open it right away.

Example of expected behavior:
- Open `Load` dialog at some random directory, e.g. `C:\`, with `PickMode.Files`.
- Write `"C:\dir1\dir2\file.txt"` (with or without quotes) on the filename input field and press Enter or click Select.
- The file is selected and `onSuccess` is invoked as usual.

The native Windows dialog goes even further, and if you write a dir path, it changes the current dir to that dir, and it even accepts relative paths. But I imagine that's more effort. There's also the question of what the behavior should be for `PickMode.Folders`, and `FilesAndFolders`. I would already be very thankful just for absolute paths in the Load dialog for `.Files`.

**Comment by yasirkula** [comment]
This is a good suggestion, thank you!
