### ISSUE TITLE
Long Load Time (Android)

### ISSUE THREAD

**Issue by ryanhlewis** [yasirkula/UnitySimpleFileBrowser#67]
**Description of the bug**

On Android, if the user selects to share a folder with a large amount of files in it, say "Camera" or "DCIM", the file browser takes an unacceptable amount of time (20+ seconds) to freeze the application and load the folder preview.

**Reproduction steps**

Put the open file browser code into an IEnumerator, and call it exactly like the Example Code provided. On Windows and Linux, it loads perfectly fine and quickly, even with gigantic folders. However, Android seems to have a different algorithm, or otherwise, is drastically slower.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2021.3.3f1
- Platform: Android
- Device: Moto G Power, Android 11 
- How did you download the plugin: Package Manager, v1.5.5

**Additional info**

05-27 15:12:18.421 I/Unity   ( 7533): Opening Android browser
05-27 15:12:18.421 I/Unity   ( 7533): <getImage>d__13:MoveNext()
05-27 15:12:18.421 I/Unity   ( 7533): UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
05-27 15:12:18.421 I/Unity   ( 7533): UnityEngine.Events.UnityEvent:Invoke()
05-27 15:12:18.421 I/Unity   ( 7533): UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
05-27 15:12:18.421 I/Unity   ( 7533): UnityEngine.InputSystem.UI.InputSystemUIInputModule:ProcessPointerButton(ButtonState&, PointerEventData)
05-27 15:12:18.421 I/Unity   ( 7533): UnityEngine.InputSystem.UI.InputSystemUIInputModule:ProcessPointer(PointerModel&)
05-27 15:12:18.421 I/Unity   ( 7533): UnityEngine.InputSystem.UI.InputSystemUIInputModule:Process()
05-27 15:12:18.421 I/Unity   ( 7533): UnityEngine.EventSystems.EventSystem:Update()
05-27 15:12:18.421 I/Unity   ( 7533):
05-27 15:13:07.297 I/Unity   ( 7533): path is content://com.android.externalstorage.documents/....

Notice the large difference between the last Unity Update() before I click on a file and return the path. This isn't me searching around. This is the application being frozen while the file manager loads, then me scrolling and clicking something in 10 seconds. All I'm doing is returning the path- no expensive byte operations. It takes no time at all once I select the actual file.

EDIT: Excellent work on your other plugin, however, [Android and IOS Native File Explorer](https://github.com/yasirkula/UnityNativeFilePicker). It works perfectly for my needs within a few minutes of setup, and is so much faster due to using the native file explorer. For anyone having a similar performance issue, I would recommend them your other plugin.

**Comment by yasirkula** [comment]
I don't have an Android 11 device but while testing on an emulator, I didn't encounter this issue. I also haven't heard about this issue before so I'm suspecting it's a device specific issue. At the moment, looking at the logs, I can't determine the cause of the issue but maybe I can reproduce and resolve it in the future.

**Comment by ryanhlewis** [comment]
I've fully migrated over to your native file explorer, as it works excellently, but the main reason I avoided this one is because of the lag. I've attached a link to a simple Unity Project I've set up to showcase the problem. I've tested to see if there's a difference between IL2CPP and Mono, and can confirm that both are laggy.
[YasirKulaTest.zip](https://github.com/yasirkula/UnitySimpleFileBrowser/files/8791787/YasirKulaTest.zip)

It does NOT lag when I select DCIM and view a small group of subfolders only. However, the moment I open a gigantic folder, like Camera one folder down, whether in-browser or from a call to opening the file browser directly to that folder, it is incredibly laggy. I assume this is because loading thousands of entries is burdensome on your algorithm, although other file managers seem to do it efficiently- perhaps the Android to Unity plugin adds too much overhead to each call for the file directory listing.

I see you tested it on an emulator, but do you have a large folder on your emulator where you can see the same results?

The issue is NOT present on Android 9, when I tested on a Samsung Galaxy S8. However, testing on Android 11 again, the issue came up on a Samsung Galaxy Note 3, as well as a Samsung Galaxy S5. Note that the stock file browser takes around half a second to display these thousand entries, while your Simple File Browser takes upwards of fifteen or twenty seconds.

**Comment by yasirkula** [comment]
Thank you for the valuable feedback! When opening a folder, I'm [passing over its whole contents to Unity](https://github.com/yasirkula/UnitySimpleFileBrowser/blob/5e6d1cdf1e968d05e00f7ba7f7ea7a3ed3fa1d31/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/FileBrowser.java#L301-L316). I'm not planning to lazy load the folder's contents (i.e. load only the visible files' details from native code) because FileBrowser.validFileEntries is used in a lot of places and it will be harder to filter the files. I'm currently passing over the files' details in a concatenated string but I'm planning to research whether or not it's possible to pass a struct array from Java to C#, which could make the process faster.

**Comment by yasirkula** [comment]
I've found out that I was first getting file ids from the files database and then for each file, querying the database 2 more times: once for the file's name and once for the file's mime type. So, if a directory had 1000 files in it, the files database was queried 2001 times. Now all those information are fetched in a single database query, so no more performance issues, hopefully 😸
