### ISSUE TITLE
SimpleFileBrowserCanvas(Clone) won't appear on Android

### ISSUE THREAD

**Issue by grox777** [yasirkula/UnitySimpleFileBrowser#68]
SimpleFileBrowserCanvas(Clone) does not open on Android. In Editor it works fine...
Worked well in previous builds, I have no idea what was changed _or what settings I might have accidentally broken._

- Write permission set to External (SdCard)
- Unity version: 2020.2.6f1
- Tested on Galaxy A30, android 11 and Bluestacks emulator
![2022-06-27_08-23-16](https://user-images.githubusercontent.com/38369760/175865654-e9d20463-fb95-4b11-8d67-f5c8e09cab2d.png)

_P.S. This was supposed to be the last test before publishing... But here we go again :'D_

**Comment by yasirkula** [comment]
That's strange. Is there anything I need to know about your setup? Like, are you putting the file browser in your scenes manually or letting the system Instantiate the file browser canvas automatically as needed? Have you modified the plugin in any noticeable way? Can you put Debug.Log lines before and after the FileBrowser.ShowLoadDialog function in your script and verify that they are both logged to Android Logcat?

**Comment by yasirkula** [comment]
Please put a `Debug.Log("Calling file browser");` line at the beginning of ShowLoadDialogCoroutine function. To see this log and other logs in logcat, you can install Unity's Android Logcat package via Package Manager. Check if "Calling file browser" is logged there and if there are any error message after that.

**Comment by grox777** [comment]
> Check if "Calling file browser" is logged there and if there are any error message after that.

_It was much easier than i thought, thank you!_

Now we know, that for some reason unity throws "object reference not set" exception... 
![2022-06-28_07-23-15](https://user-images.githubusercontent.com/38369760/176091907-3c5797ef-0032-4ba7-97ef-ea12c67f709e.png)

`06.28 07:20:09.913 27683 27697 Info Unity UnityEngine.EventSystems.StandaloneInputModule:Process()
06.28 07:20:09.913 27683 27697 Info Unity 
06.28 07:20:09.923 27683 27697 Error Unity NullReferenceException: Object reference not set to an instance of an object.
06.28 07:20:09.923 27683 27697 Error Unity   at SimpleFileBrowser.FileBrowser.set_PickerMode (SimpleFileBrowser.FileBrowser+PickMode value) [0x00000] in <00000000000000000000000000000000>:0 
06.28 07:20:09.923 27683 27697 Error Unity   at SimpleFileBrowser.FileBrowser.ShowDialogInternal (SimpleFileBrowser.FileBrowser+OnSuccess onSuccess, SimpleFileBrowser.FileBrowser+OnCancel onCancel, SimpleFileBrowser.FileBrowser+PickMode pickMode, System.Boolean allowMultiSelection, System.Boolean acceptNonExistingFilename, System.String initialPath, System.String initialFilename, System.String title, System.String submitButtonText) [0x00000] in <00000000000000000000000000000000>:0 
06.28 07:20:09.923 27683 27697 Error Unity   at SimpleFileBrowser.FileBrowser.ShowLoadDialog (SimpleFileBrowser.FileBrowser+OnSuccess onSuccess, SimpleFileBrowser.FileBrowser+OnCancel onCancel, SimpleFileBrowser.FileBrowser+PickMode pickMode, System.Boolean allowMultiSelection, System.String initialPath, System.String initialFilename, System.String title, System.String loadButtonText) [0x00000
06.28 07:20:10.033 363 1955 Info BufferQueueProducer [SurfaceView](this:0xb3190400,id:565,api:1,p:27683,c:363) queueBuffer: fps=14.93 dur=1071.55 max=94.59 min=39.17
06.28 07:20:10.413 16334 16782 Debug NetworkController.MobileSignalController(1/2) onSignalStrengthsChanged signalStrength=SignalStrength: 31 99 -31 -200 -31 -200 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 0x4 gsm|lte level=4
06.28 07:20:10.413 16334 16782 Debug NetworkController.MobileSignalController(1/2) getMobileIconGroup(): 0
`

**Comment by yasirkula** [comment]
Can you select the SimpleFileBrowserCanvas prefab in Project window and check its Inspector to verify that all of its variables are assigned values?

**Comment by grox777** [comment]
> Can you select the SimpleFileBrowserCanvas prefab in Project window and check its Inspector to verify that all of its variables are assigned values?

_Seems like all of them are assigned_
![2022-06-28_09-59-57](https://user-images.githubusercontent.com/38369760/176114404-5ea49d3d-9956-4606-ae57-2d33ad50c48a.png)
![2022-06-28_10-00-11](https://user-images.githubusercontent.com/38369760/176114409-8d279255-0a7e-4f82-a03e-d0d41c8f8a85.png)

**Comment by yasirkula** [comment]
Oh.. That was an unexpected solution, honestly. I'll probably give it a try myself.
