### ISSUE TITLE
UWP compatibility

### ISSUE THREAD

**Issue by Lamarn** [yasirkula/UnitySimpleFileBrowser#7]
At the moment I am trying to build a project including the file browser to UWP, but I get errors. I can not use Environment.SpecialFolder (and some more functionalities in this class) which seems to be not included in UWP. Maybe there is a quick fix. For today I will just try to include the UWP file browser. Of course it would be cool, if this file browser could do this too.

**Comment by yasirkula** [comment]
I'll see what I can do. Thanks for reporting this.

**Comment by yasirkula** [comment]
I've fixed the errors for convenience but I couldn't get the plugin to work correctly with UWP. I guess it is only possible to use [native dialogs](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers) on UWP. So, this plugin won't be supporting UWP.

Thanks again for reporting the errors.
