### ISSUE TITLE
File and folder entries are invisible and unclickable in Unity 2021.3.6

### ISSUE THREAD

**Issue by TdXYZ** [yasirkula/UnitySimpleFileBrowser#70]
**Description of the bug**

When opening a file browser for loading up files, there are no files and folders being displayed. The entries exist in the hierarchy, but they are invisible. They cannot be clicked either.

**Reproduction steps**

- Open the file browser by calling ShowLoadDialog
- There are no files or folders shown even when clicking through the quick links

**Platform specs**

- Unity version: 2021.3.6f1
- Platform: macOS
- How did you download the plugin: Through .unitypackage. Latest version was used.

**Additional info**

Everything still works in Unity 2020.3, but not in 2021.3

**Comment by yasirkula** [comment]
It's likely a Unity bug introduced in 2021.3.2 or later (file browser works fine in 2021.3.1). For a temporary solution, please see: https://forum.unity.com/threads/simple-file-browser-open-source.441908/page-12#post-8269698

**Comment by nickolas52468** [comment]
I Just **Removed** the **Canvas** and **Grahic Raycaster** from 
_SimpleFileBrowserCanvas > SimpleFileBrowserWindow > Padding > MidView > Padding > Files_ following the link up there and works! 
thanks!

**Comment by yasirkula** [comment]
I've also created a bug report but it hasn't been seen yet. Hopefully they'll resolve this issue soon.

**Comment by miventech** [comment]
> I Just **Removed** the **Canvas** and **Grahic Raycaster** from _SimpleFileBrowserCanvas > SimpleFileBrowserWindow > Padding > MidView > Padding > Files_ following the link up there and it worked! thanks!

THANKS !!! <3

**Comment by bradhannah** [comment]
> I Just **Removed** the **Canvas** and **Grahic Raycaster** from _SimpleFileBrowserCanvas > SimpleFileBrowserWindow > Padding > MidView > Padding > Files_ following the link up there and it worked! thanks!

Amazing - can confirm this did the trick for me as well!

**Comment by yasirkula** [comment]
Possibly the same Issue: [https://issuetracker.unity3d.com/is...vating-and-reactivating-the-parent-gameobject](https://issuetracker.unity3d.com/issues/ui-elements-are-no-longer-rendered-when-deactivating-and-reactivating-the-parent-gameobject). If it's, then it'll be fixed in 2021.3.9f1 by Unity, thankfully.

**Comment by yasirkula** [comment]
If anyone gets to test whether or not this issue is fixed on 2021.3.9f1 and newer, please let me know 🤩

**Comment by yasirkula** [comment]
@EdsartBS Thank you for confirming it 🥳 I'm now closing this Issue since it's linked in the [FAQ](https://github.com/yasirkula/UnitySimpleFileBrowser#faq) for users that experience it on problematic 2021.3 versions.

**Comment by yasirkula** [comment]
Reminder for people who visit this thread: if you're using one of the problematic Unity versions and upgrading to the latest LTS isn't possible, please delete the aforementioned components from all nested canvases: #74

**Comment by evmarcus** [comment]
I'm trying to use the software on a project in Unity 2021.3.45f1, and I'm running into this issue. I've tried the band-aid solution of removing the canvases, but they weren't there to begin with in the most recent version of this software. Is there something else that may be causing this problem? I am unable to switch Unity versions.

![Image](https://github.com/user-attachments/assets/12096ed8-68cb-4038-8112-e3237008f5a1)

**Comment by yasirkula** [comment]
@evmarcus Package uses TextMesh Pro. Do you have its essential files installed (`Window-TextMeshPro-Import TMP Essential Resources`)? There must be at least one TMP_FontAsset in the project. Alternatively, you can use [v1.6.6 of the plugin](https://github.com/yasirkula/UnitySimpleFileBrowser/releases) which doesn't use TMP but you'll be missing some fixes and improvements.
