### ISSUE TITLE
A question about compatibility

### ISSUE THREAD

**Issue by Loki-Hornsby** [yasirkula/UnitySimpleFileBrowser#71]
Hiya - i'm extremely sorry to bother you but is this plugin suitable for Mac and Linux? I couldn't see any information about linux specifically but i'm pretty sure it does work on Mac - just confirming because i'm using this in a comercial product (i've linked a credit to you  and your links in my games credit system - if you'd like any extra links added or removed please contact me here or at lokihornsby@gmail.com - the links put are your website and your asset store page) 
I'd also like to thankyou an *extreme* amount for making this asset free - i really do appreciate it! 😄

**Comment by yasirkula** [comment]
Thank you for giving credits, I appreciate it! I haven't tested the plugin on either of those platforms myself but on Mac, when sandboxing is enabled, the plugin apparently [can't access most of the files](https://github.com/yasirkula/UnitySimpleFileBrowser/issues/66#issuecomment-1140255520). I'll work on that issue.

**Comment by Loki-Hornsby** [comment]
Awesome! - again thankyou - i've spent 2 days looking for a system for a system for dragging and dropping files only to give up when finding it's bassically impossible without building the game and running only on windows - then of course finding theres a limited amount of resources for file explorers as well (especially working / free ones).

**Comment by yasirkula** [comment]
My plugin doesn't have drag&drop functionality, though; I mean if you're planning to drag&drop files from your OS' file browser to the Unity app's window.

**Comment by Loki-Hornsby** [comment]
Ah sorry i think i wasn't clear enough - i gave up looking for drag and drop systems after 2 days of searching for one and decided to instead try and look for file browsers - and it was very hard to find one too until of course i came across yours ;)
