### ISSUE TITLE
Suggestion: Expose DocumentsContract.isChildDocument

### ISSUE THREAD

**Issue by juh9870** [yasirkula/UnitySimpleFileBrowser#73]
As you mentioned in discord, there is a function DocumentsContract.isChildDocument, which allows to check if document is inside another document. It would be very helpful to have this function exposed for easy access.

**Comment by yasirkula** [comment]
Can you update the plugin with the version inside this zip archive and give FileBrowserHelpers.IsPathChildOfAnother a try on both standalone (testing in Editor suffices) and Android: [SimpleFileBrowser.zip](https://github.com/yasirkula/UnitySimpleFileBrowser/files/9791713/SimpleFileBrowser.zip). Please check if the function returns true not only for direct descendants but also for grand descendants.

**Comment by juh9870** [comment]
Sure, I will try to check it tomorrow, thanks!

**Comment by yasirkula** [comment]
Added with https://github.com/yasirkula/UnitySimpleFileBrowser/commit/1e8a795d1569bcdfbab4d1983f1da9cd559c3741
