### ISSUE TITLE
How to get the SimpleFileBrowserCanvas(Clone) reference after it spawns on my scene in script?

### ISSUE THREAD

**Issue by sstamatis01** [yasirkula/UnitySimpleFileBrowser#79]
I have been using the SimpleFileBrowser just fine my VR project, however one minor setback is the fact that I cant edit `SimpleFileBrowserCanvas(Clone)` position in runtime because I cannot find its refence in my script.  Basically I always want it to spawn in front of my player so I need its reference to change its position whenever I call yield `return FileBrowser.WaitForLoadDialog(FileBrowser.PickMode.FilesAndFolders, true, null, null, "Load Files and Folders", "Load");`

The reason why this happens is because it spawns as a new scene (DontDestroyOnLoad) which unfortunately is created dynamically and thus I cannot register it in my build in order to switch between scenes with `SceneManager.LoadScene` package. Searching the object with `Find `wont work since I m looking in my main scene. 

This should be possible to do somehow but I am not very experienced with Unity to do it myself. I would appreciate if someone knows who to do this.
![filebrowser_issue](https://user-images.githubusercontent.com/33598252/220909858-7c364bb8-55fd-4330-91fe-da4737dc788d.png)

**Comment by yasirkula** [comment]
Hi! If you wish, you can put an instance of SimpleFileBrowserCanvas to your scene and reference it in your scripts. Or, you can get the file browser via `FindObjectOfType<FileBrowser>()` after calling WaitForLoadDialog for the first time.
