### ISSUE TITLE
Can I use It in world Canvas to integrate It in VR?

### ISSUE THREAD

**Issue by elblogbruno** [yasirkula/UnitySimpleFileBrowser#8]
Normally It behaves in camera overlay and I want It to be in world Canvas.

Also there's some way to use it just to see files not load or save?
Thanks a lot for everything!

**Comment by yasirkula** [comment]
You can instantiate an instance of SimpleFileBrowserCanvas in your scene and make it a World Canvas. After adjusting its position, you can apply the changes to prefab.

To just see files, you can disable the Save/Load button (and any other UI elements you find redundant) and apply the changes to prefab, again.

**Comment by elblogbruno** [comment]
Thanks a lot! I'll try it out

**Comment by elblogbruno** [comment]
Just got it working perfectly!
Thanks  a lot for this!
[https://drive.google.com/file/d/1JUC9MKBfbXxUU3Ax3_o-mLdmbNIi4cTF/view?usp=sharing](url)

**Comment by yasirkula** [comment]
Glad to hear it :)

**Comment by elblogbruno** [comment]
Now that I know  you are a unity expert, you know how to render a website on a world space canvas?

**Comment by yasirkula** [comment]
AFAIK, you have to use a plugin for this. You can google "unity webview github" to find some open-source solutions.

**Comment by elblogbruno** [comment]
Yeah I found one's but they overlay the web on the screen and I haven't found any plugin that renders on world space canvas so I can use it in vr.
Thanks anyway!

**Comment by yaalisri** [comment]
@elblogbruno How did you implement this? Can you pls post sample code and scene details pls?
