### ISSUE TITLE
Changing skin during runtime throws error

### ISSUE THREAD

**Issue by SchroerDev** [yasirkula/UnitySimpleFileBrowser#81]
**Description of the bug**

Changing skin during runtime throws error when _ShowResizeCursor=false_:
```
MissingReferenceException: The variable resizeCursorHandler of FileBrowser doesn't exist anymore.
You probably need to reassign the resizeCursorHandler variable of the 'FileBrowser' script in the inspector.
UnityEngine.Component.GetComponent[T] () (at <86acb61e0d2b4b36bc20af11093be9a5>:0)
SimpleFileBrowser.FileBrowser.RefreshSkin () (at Assets/UnitySimpleFileBrowser/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs:1248)
SimpleFileBrowser.FileBrowser.Update () (at Assets/UnitySimpleFileBrowser/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs:895)
```

**Reproduction steps**
1. Disable the property _Show Resize Cursor_ in file browser prefab
2. Run in Editor
3. Open file browser
4. Select the file browser game object
5. Change the _Skin_ property in _FileBrowser_ component (e.g from _LightSkin_ to _DarkSkin_)
=> Error!

**Platform specs**
- Unity version: *2022.1.20f*
- Platform: *Android/Editor*
- How did you download the plugin: *GitHub*

**Additional info**
Filebrowser.cs Line 861 destroys the resizeCursorHandler object and line 1248 calls 
_resizeCursorHandler.GetComponent<Image>()_.  
  
**Possible solution**
Remove:  
```cs
			Image windowResizeGizmo = resizeCursorHandler.GetComponent<Image>();
			windowResizeGizmo.color = m_skin.WindowResizeGizmoColor;
			windowResizeGizmo.sprite = m_skin.WindowResizeGizmo;
```
Add:  
```cs            
            if (resizeCursorHandler)
            {
                Image windowResizeGizmo = resizeCursorHandler.GetComponent<Image>();
                windowResizeGizmo.color = m_skin.WindowResizeGizmoColor;
                windowResizeGizmo.sprite = m_skin.WindowResizeGizmo;
            }
```

**Comment by yasirkula** [comment]
Thank you for the detailed bug report!

**Comment by SchroerDev** [comment]
You're welcome! Thank YOU for the great asset!
