### ISSUE TITLE
Android Showing Different Menu

### ISSUE THREAD

**Issue by krishrajchal** [yasirkula/UnitySimpleFileBrowser#84]
**Description of the bug**

When I used the plugin before, I remember being able to select files from the Internal Storage.
Now, when I press the browse button, it shows "Can't use this folder, To protect your privacy, choose another folder." 

I set these permissions in the manifest:
READ_EXTERNAL_STORAGE
WRITE_EXTERNAL_STORAGE
MANAGE_EXTERNAL_STORAGE

tools:node is replace
requestLegacyExternalStorage is true 

**Reproduction steps**

Open using ShowDialog with allowMultiSelection true and PickMode to FilesAndFolders
Press on browse

**Platform specs**

- Unity version:  2022.3.3f1
- Platform: Android
- Device: Samsung Galaxy A12, Android 12
- How did you download the plugin: Updated/downloaded from GitHub

**Additional info**

No errors relating to the plugin or unity:
libprocessgroup      set_timerslack_ns write failed: Operation not permitted

**Comment by yasirkula** [comment]
Unfortunately, Android prevents selecting the root directory and Downloads on newer Android versions while "Browse..."ing. Overcoming it requires MANAGE_EXTERNAL_STORAGE permission being granted from Settings but unless your app is strictly a file browser app, Google Play can reject your app due to this permission.

You man also use [NativeFilePicker](https://github.com/yasirkula/UnityNativeFilePicker) if you're only interested in picking files (and you're picking common file types like pdf, jpg, etc.).

**Comment by krishrajchal** [comment]
When I was trying to make it work, I had a plugin that asked for the MANAGE_EXTERNAL_STORAGE permission. Even with permission, it still had that menu.

**Comment by yasirkula** [comment]
Hmm, could you set this field to false via Reflection and try again: https://github.com/yasirkula/UnitySimpleFileBrowser/blob/db6c74e751238113ca9d1d19c19c580e6628687d/Plugins/SimpleFileBrowser/Scripts/FileBrowserHelpers.cs#L80

```csharp
#if !UNITY_EDITOR && UNITY_ANDROID
typeof(FileBrowserHelpers).GetField("m_shouldUseSAF", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(null, (bool?)false);
#endif
```

**Comment by krishrajchal** [comment]
Where does the reflection go?

**Comment by yasirkula** [comment]
Awake is a good candidate.

**Comment by krishrajchal** [comment]
NullReferenceException on the reflection part.

**Comment by yasirkula** [comment]
Did you include `#if` part in your code? You must, if you didn't.

**Comment by krishrajchal** [comment]
Good thing it works but, there are some warnings that may prevent it from working on the Google Play Store. I will try to fix them:

Accessing hidden method Landroid/os/storage/StorageVolume;->getPath()Ljava/lang/String; (max-target-q,test-api, reflection, denied)

If this is a platform test consider enabling VMRuntime.ALLOW_TEST_API_ACCESS change id for this package.

**Comment by yasirkula** [comment]
Does replacing SimpleFileBrowser.aar with the one [inside this zip archive](https://github.com/yasirkula/UnitySimpleFileBrowser/files/12138493/SimpleFileBrowser.zip) resolve the issue?

**Comment by krishrajchal** [comment]
That worked, now, those warnings are not there and the nav button is visible too (previously not showing).
