### ISSUE TITLE
Log Spam: Invalid Unicode Error

### ISSUE THREAD

**Issue by JoshMayberry** [yasirkula/UnitySimpleFileBrowser#85]
My console is spammed with the following message every second:

```
The character with Unicode value □ was not found in the [] font asset or any potential fallbacks. It was replaced by Unicode character □.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

One instance of this is on the Package Manager page at the end: `GitHub Sponsors □ (https://github.com/sponsors/yasirkula)`

I'm not sure where the others are, but I get the error even when the Package Manager is not open- so perhaps it is in other places as well?

**Comment by yasirkula** [comment]
TextMesh Pro can throw these errors when an unknown character is introduced. If these aren't related to TMP, I'm totally clueless about the issue. Can you provide step-by-step repro steps?

**Comment by JoshMayberry** [comment]
(You have done an amazing job with this project btw. :) Love it!)

Sure. Here's a consistent way to trigger it for me:

1. Open the Package Manager
2. Click on your package
3. The console stars to get filled with messages
4. If I scroll the inspector window part, the messages continue to be posted

My bet is that the character `□` (which for me appears as an outline of a square) in the final line `GitHub Sponsors □ (https://github.com/sponsors/yasirkula)` is causing the issue.

The resolution (I think) would be to remove all non-standard characters from your project.

Here is consistent another way to trigger it:
1. In the project folder, navigate to the folder containing this asset
2. Click on any of the files.
3a. Continuing to click on files in the inspector window causes the log spam.
3b. Just having one of the files selected will cause the console error to be posted every 1 to 3 seconds
It does not seem to matter which file from your project I have selected- the error keeps happening.

I did not notice any `□` characters in the files I searched- so perhaps Unity is getting mad about such characters in other files and by touching one file in the project it actually touches the others? I'm not exactly sure how it is implemented.

![image](https://github.com/yasirkula/UnitySimpleFileBrowser/assets/11482252/7ea0c486-f137-48f6-8252-ab26dde25af6)

I only get this error when interacting with files form your project.

**Comment by yasirkula** [comment]
On both 2022.2.13f1 and 2022.3.8f1, I get those logs only when selecting Runtime File Browser from Package Manager's My Assets section. For me the log is logged only twice. It isn't constantly logged as I scroll anywhere or when I select an asset in the plugin. My guess is that your version of Unity has a bug that is resolved in a following release.

**Comment by yasirkula** [comment]
BTW, since the Package Manager description is copied from Asset Store, the problematic character is this and I'd like to keep it in my Asset Store description since it doesn't cause issues (for me) in latest Unity releases:

![image](https://github.com/yasirkula/UnitySimpleFileBrowser/assets/10211608/f3d85af3-6207-48a5-8c57-887082237689)

**Comment by JoshMayberry** [comment]
I'm using version 2023.1.4f1.

**Comment by yasirkula** [comment]
Hmm, I don't have 2023 installed yet. I hope they resolve this issue in a future update and I may give it another shot with 2023 when I install it.
