### ISSUE TITLE
WebGL Methods

### ISSUE THREAD

**Issue by JoshMayberry** [yasirkula/UnitySimpleFileBrowser#86]
The file picker does not seem to work for games built for WebGL.

Could we either get some alternative functions that would make the browser's [native file picker](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker) show up instead- or have the `FileBrowserHelpers.ReadTextFromFile` method detect we are in a WebGL app and use the browser's native file picker instead?

Here's what it looks like when I use the file picker on a WebGL project in itch.io:
![image](https://github.com/yasirkula/UnitySimpleFileBrowser/assets/11482252/4934f717-57f1-434c-a711-91b2192d078b)

**Comment by yasirkula** [comment]
I've mentioned this in the [FEATURES section](https://github.com/yasirkula/UnitySimpleFileBrowser#features) actually but it is easy to miss it:

> **NOTE:** _Universal Windows Platform (UWP)_ and _WebGL_ platforms aren't supported!

I currently don't have plans to support WebGL but do check this out: https://github.com/gkngkc/UnityStandaloneFileBrowser

**Comment by JoshMayberry** [comment]
No problem! :) Thanks for the link.
