### ISSUE TITLE
File Access does not work on quest 2

### ISSUE THREAD

**Issue by thmasn** [yasirkula/UnitySimpleFileBrowser#87]
it seems to be i am the first one trying to use the file browser on a quest 2!

**Description of the bug**

File Access on the quest 2 seems to be limited to the apllications own folder.
everything works perfectly in the application folder which is opened by default.
but, even after granting rights to another folder to the application, only the application folder is shown. no new quick links appear on the left side of the file browser, no other files are visible in the right side item view.

**Reproduction steps**

- use file browser package
- small adjustments for vr ui etc.
- verify it is working well on android, no issues on an android smartphone
- deploy to quest 2
- try to follow the same steps as we did earlier on a android smartphone
- unable to select a new folder location
[video showing what happens](https://youtu.be/z1EIkwhHWEk)

**Platform specs**
- Unity version: *2021.3.29f1* on Windows
- Device: "Quest 2 version 56"

- How did you download the plugin: *GitHub, latest version as of today*

**Additional info**

no errors in logcat. i did add custom debug logs, which tell me:
in FetchPersistedSAFQuickLinks(), resultRaw is always "0", which causes the function to return.
my guess is that this is the cause of no quick links appearing. why is it zero? i do not know...

**Comment by yasirkula** [comment]
Can you try running this code in Awake/Start:

```csharp
#if !UNITY_EDITOR && UNITY_ANDROID
typeof(SimpleFileBrowser.FileBrowserHelpers).GetField("m_shouldUseSAF", BindingFlags.NonPublic | BindingFlags.Static).SetValue(null, (bool?)false);
#endif
```

**Comment by thmasn** [comment]
i had to add
"using System.Reflection;"
and added the code to the beginning of Awake()

now it works perfectly, i can even see all the folders on the device!

i have no idea why it works, but thank you a lot for the help!

**Comment by yasirkula** [comment]
You're welcome. I don't know why it works either, I've just stopped asking my question some time ago 🙈

**Comment by 414726193** [comment]
I think I am copying the data to the private directory in this part of the code because I was concerned that Android 10+ might not support reading the file directly. How can I improve this?

    void OnFilesSelected(string[] filePaths, System.Action<bool, string> actionResul)
    {
        // Print paths of the selected files
        for (int i = 0; i < filePaths.Length; i++)
            Debug.Log(filePaths[i]);

        // Get the file path of the first selected file
        string filePath = filePaths[0];
      //  byte[] bytes = FileBrowserHelpers.ReadBytesFromFile(filePath);
        // Or, copy the first file to persistentDataPath
        string destinationPath = Path.Combine(Application.persistentDataPath, FileBrowserHelpers.GetFilename(filePath));
        FileBrowserHelpers.CopyFile(filePath, destinationPath);

        actionResul(true, destinationPath);
        // Read the bytes of the first file via FileBrowserHelpers
        // Contrary to File.ReadAllBytes, this function works on Android 10+, as well
        //byte[] bytes = FileBrowserHelpers.ReadBytesFromFile(filePath);
       // selectimagr(filePath);
        // Or, copy the first file to persistentDataPath
       // string destinationPath = Path.Combine(Application.persistentDataPath, FileBrowserHelpers.GetFilename(filePath));
      //  FileBrowserHelpers.CopyFile(filePath, destinationPath);
    }
