### ISSUE TITLE
GLB and JSON files not appearing Quest Pro

### ISSUE THREAD

**Issue by SashelI** [yasirkula/UnitySimpleFileBrowser#89]
**Description of the bug**

Hi,

Thanks for the asset ! It works well on the Quest Pro (Android), but I've got a problem : .glb and .json files are not appearing in the browser, nor listed by system.IO when retrieving directory info. It works well in the editor when removing the "!Unity_Editor" preprocessing for testing, but once inside the quest the files are non existent. (but png files in the same folder are here). 

I've tried using Directory.GetFiles(path) instead of GetFileSystemInfo, but same. The "show hidden files" button doesn't help, and there is no log message.

**Reproduction steps**

- Open the browser on a Quest Pro device
- Try to load a .glb or .json file

![Capture d’écran 2023-10-13 145645](https://github.com/yasirkula/UnitySimpleFileBrowser/assets/22128247/06cf4e17-9412-4f22-b7f2-ef253087dcd8)

![com oculus vrshell-20231013-145755](https://github.com/yasirkula/UnitySimpleFileBrowser/assets/22128247/e926aa38-cb5d-4db1-bee5-5a5498af3658)

**Platform specs**

- Unity version: *2021.3.25f1*
- Platform: *Android*
- Device: *Quest Pro, Android 12L*
- How did you download the plugin: *Asset Store*

**Additional info**

Manisfest File :
`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" android:installLocation="auto">
	<uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove" />
	<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" tools:node="remove" />
	<application android:label="@string/app_name" android:icon="@mipmap/app_icon" android:allowBackup="false" android:requestLegacyExternalStorage="true">
		<activity android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" android:configChanges="locale|fontScale|keyboard|keyboardHidden|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode" android:launchMode="singleTask" android:name="com.unity3d.player.UnityPlayerActivity" android:excludeFromRecents="true" android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="false" />
		<meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only" />
	</application>
	<uses-feature android:name="android.hardware.vr.headtracking" android:version="1" android:required="true" />
	<uses-feature android:name="com.oculus.feature.PASSTHROUGH" android:required="true" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>
	<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
</manifest>`

![image](https://github.com/yasirkula/UnitySimpleFileBrowser/assets/22128247/f2c57926-1c5b-4efa-a58f-fdf574c1f778)

**Comment by yasirkula** [comment]
Is this png file downloaded by your app? If you copy an arbitrary png file from your computer to Downloads, can it be seen by SimpleFileBrowser? BTW are/were any Storage permission dialogs displayed while opening the file browser?

**Comment by SashelI** [comment]
> Is this png file downloaded by your app? If you copy an arbitrary png file from your computer to Downloads, can it be seen by SimpleFileBrowser? BTW are/were any Storage permission dialogs displayed while opening the file browser?

Yup the png was copied from my computer, as were the .glb and the .json :) Nope no storage permission dialogue, well no more I accepted everything it asked once

**Comment by yasirkula** [comment]
If you log contents of Directory.GetFiles("/storage/emulated/0/Download") in your own C# script, does it contain the GLB and JSON files?

**Comment by SashelI** [comment]
> If you log contents of Directory.GetFiles("/storage/emulated/0/Download") in your own C# script, does it contain the GLB and JSON files? And does removing MANAGE_EXTERNAL_STORAGE permission somehow have any effect?

Hey, I just tested, Logging Directory.GetFiles("/storage/emulated/0/Download") from my script only shows one file (the png) and the MANAGE_EXTERNAL_STORAGE permission is in fact useless in this, I added it afterwards in hopes of making it work but nah ^^"

**Comment by yasirkula** [comment]
I think we need to figure out why Directory.GetFiles fails in the first place. Since it's a built-in .NET function, this issue isn't directly caused by SimpleFileBrowser. If the Directory.GetFiles issue can be resolved somehow, then I believe SimpleFileBrowser will work without any issues.

For the time being, I don't have time to research this. If you find useful resources related to this issue in your own research, please let me know.

**Comment by yasirkula** [comment]
Thank you for sharing your solution! I'll add a link to it from FAQ. I wish [NativeFilePicker](https://github.com/yasirkula/UnityNativeFilePicker) worked with Quest which wouldn't have this issue but unfortunately AFAIK it doesn't, so your solution is the only way to go at the moment.

**Comment by SashelI** [comment]
Thanks. Yeah I've tried native file picker before this one, and quickly realized the Android 12 + Meta combo will be a nightmare to figure out x)

**Comment by yasirkula** [comment]
The known Quest issue is, file picker's result is allegedly not sent to the device until the app is minimized and then maximized. If that wasn't an issue, I think it would work wonderfully.
